name = "jeb-dark"
version = "0.1.0"
author = "JebGy"
display-name = "Jeb-Theme"
description = "The JebGy theme for Lapce"
wasm = "lapce-rust.wasm"

[activation]
language = ["rust"]
workspace-contains = ["*/Cargo.toml"]
